

###AUTOSTART APPLICATIONS HERE


exec-once = waybar & hyprpaper
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = swaync
exec-once = swww-daemon
exec-once = bluetoothctl connect 24:DF:17:23:66:66

