cursor            #80d4db
cursor_text_color #00363a

foreground            #dde4e4
background            #090f10
selection_foreground  #1b3436
selection_background  #b1cbce
url_color             #b1cbce

#: black 000000 767676
color0  #0e1415
color8  #303636
#: red cc0403 f2201f
color1  #000000
color9  #094c53
#: green 19cb00 23fd00
color2  #b1cbce
color10 #cce8ea
#: yellow cecb00 fffd00
color3  #b7c7ea
color11 #d7e3ff
#: blue 0d73cc 1a8fff
color4  #004f54
color12 #80d4db
#: magenta cb1ed1 fd28ff
color5  #324b4d
color13 #b1cbce
#: cyan 0dcdcd 14ffff
color6  #374764
color14 #b7c7ea
#: white dddddd ffffff
color7  #bec8c9
color15 #dde4e4

mark1_foreground #002022
mark1_background #9df0f8
mark2_foreground #051f21
mark2_background #cce8ea
mark3_foreground #0a1b36
mark3_background #d7e3ff

active_tab_foreground #00363a
active_tab_background #80d4db
inactive_tab_foreground #9df0f8
inactive_tab_background #004f54

active_border_color #80d4db
inactive_border_color #00363a
# bell_border_color #ff5a00
